// Meet country for NON-Portuguese cities (3-letter codes).
// The data has no meet-country field, so this is a manual lookup: any city not
// listed here is assumed to be in Portugal and shown with no prefix.
// Extend this list as new foreign cities appear with more clubs.
export const CITY_COUNTRY = {
  'Abu Dhabi': 'UAE',
  Angers: 'FRA',
  'Aulnay-Sous-Bois': 'FRA',
  Baku: 'AZE',
  Barcelona: 'ESP',
  Belgrade: 'SRB',
  Beograd: 'SRB',
  Bethune: 'FRA',
  Broenshoej: 'DEN',
  Budapest: 'HUN',
  Cadiz: 'ESP',
  'Canet-En-Roussillon': 'FRA',
  Copenhagen: 'DEN',
  Cordoba: 'ESP',
  Daegu: 'KOR',
  Doha: 'QAT',
  Dublin: 'IRL',
  Eindhoven: 'NED',
  Espoo: 'FIN',
  Essen: 'GER',
  Futog: 'SRB',
  Geneva: 'SUI',
  Gijon: 'ESP',
  Glasgow: 'GBR',
  'Gorzow Wlkp.': 'POL',
  Gwangju: 'KOR',
  Hangzhou: 'CHN',
  Helsinki: 'FIN',
  Herning: 'DEN',
  Istanbul: 'TUR',
  Kazan: 'RUS',
  'La Mirada': 'USA',
  Lausanne: 'SUI',
  Lodz: 'POL',
  Lublin: 'POL',
  Luanda: 'ANG',
  Luxembourg: 'LUX',
  Madrid: 'ESP',
  'Mairena Del Aljarafe': 'ESP',
  Malaga: 'ESP',
  Massy: 'FRA',
  Milwaukee: 'USA',
  Montpellier: 'FRA',
  Moscow: 'RUS',
  Napoli: 'ITA',
  Netanya: 'ISR',
  Oran: 'ALG',
  Ostrava: 'CZE',
  Otopeni: 'ROU',
  Paris: 'FRA',
  'Pontault-Combault': 'FRA',
  Pontevedra: 'ESP',
  Prague: 'CZE',
  Rennes: 'FRA',
  Riesa: 'GER',
  Rijeka: 'CRO',
  Rio: 'BRA',
  Rome: 'ITA',
  Sabadell: 'ESP',
  'Saint-Etienne': 'FRA',
  'Saint-Germain-En-Laye': 'FRA',
  'San Marino': 'SMR',
  Shanghai: 'CHN',
  Stockholm: 'SWE',
  Sydney: 'AUS',
  Tampere: 'FIN',
  Tarragona: 'ESP',
  Tokyo: 'JPN',
  Uster: 'SUI',
  'Val Parisis': 'FRA',
  Vichy: 'FRA',
  Vilnius: 'LTU',
  Windsor: 'CAN',
  Worb: 'SUI',
  Zagreb: 'CRO',
};

// "Gijon (ESP)" for foreign cities; plain city name for Portuguese ones.
export function formatCity(city) {
  if (!city) return '';
  const code = CITY_COUNTRY[city];
  return code ? `${city} (${code})` : city;
}
