// Meet country for NON-Portuguese cities (3-letter codes).
// The data has no meet-country field, so this is a manual lookup: any city not
// listed here is assumed to be in Portugal and shown with no prefix.
// Extend this list as new foreign cities appear with more clubs.
export const CITY_COUNTRY = {
  'Abu Dhabi': 'UAE',
  Angers: 'FRA',
  'Aulnay-Sous-Bois': 'FRA',
  Baku: 'AZE',
  Barcelona: 'ESP',
  Belgrade: 'SRB',
  Beograd: 'SRB',
  Bethune: 'FRA',
  Broenshoej: 'DEN',
  Budapest: 'HUN',
  Cadiz: 'ESP',
  'Canet-En-Roussillon': 'FRA',
  Copenhagen: 'DEN',
  Cordoba: 'ESP',
  Daegu: 'KOR',
  Doha: 'QAT',
  Dublin: 'IRL',
  Eindhoven: 'NED',
  Espoo: 'FIN',
  Essen: 'GER',
  Futog: 'SRB',
  Geneva: 'SUI',
  Gijon: 'ESP',
  Glasgow: 'GBR',
  'Gorzow Wlkp.': 'POL',
  Gwangju: 'KOR',
  Hangzhou: 'CHN',
  Helsinki: 'FIN',
  Herning: 'DEN',
  Istanbul: 'TUR',
  Kazan: 'RUS',
  'La Mirada': 'USA',
  Lausanne: 'SUI',
  Lodz: 'POL',
  Lublin: 'POL',
  Luanda: 'ANG',
  Luxembourg: 'LUX',
  Madrid: 'ESP',
  'Mairena Del Aljarafe': 'ESP',
  Malaga: 'ESP',
  Massy: 'FRA',
  Milwaukee: 'USA',
  Montpellier: 'FRA',
  Moscow: 'RUS',
  Napoli: 'ITA',
  Netanya: 'ISR',
  Oran: 'ALG',
  Ostrava: 'CZE',
  Otopeni: 'ROU',
  Paris: 'FRA',
  'Pontault-Combault': 'FRA',
  Pontevedra: 'ESP',
  Prague: 'CZE',
  Rennes: 'FRA',
  Riesa: 'GER',
  Rijeka: 'CRO',
  Rio: 'BRA',
  Rome: 'ITA',
  Sabadell: 'ESP',
  'Saint-Etienne': 'FRA',
  'Saint-Germain-En-Laye': 'FRA',
  'San Marino': 'SMR',
  Shanghai: 'CHN',
  Stockholm: 'SWE',
  Sydney: 'AUS',
  Tampere: 'FIN',
  Tarragona: 'ESP',
  Tokyo: 'JPN',
  Uster: 'SUI',
  'Val Parisis': 'FRA',
  Vichy: 'FRA',
  Vilnius: 'LTU',
  Windsor: 'CAN',
  Worb: 'SUI',
  Zagreb: 'CRO',
  // --- Added after loading all clubs (national teams & clubs competing abroad) ---
  Aachen: 'GER',
  Abymes: 'FRA',
  Agen: 'FRA',
  Alcala: 'ESP',
  'Alcala De Guadaira': 'ESP',
  Amsterdam: 'NED',
  Antwerp: 'BEL',
  Antwerpen: 'BEL',
  Athens: 'GRE',
  Attichy: 'FRA',
  Badajoz: 'ESP',
  Bangkok: 'THA',
  'Banska Bystrica': 'SVK',
  Bastia: 'FRA',
  Beijing: 'CHN',
  'Belo Horizonte': 'BRA',
  Berlin: 'GER',
  Boras: 'SWE',
  Bordeaux: 'FRA',
  Bozen: 'ITA',
  Bratislava: 'SVK',
  Brovary: 'UKR',
  Bucuresti: 'ROU',
  'Buenos Aires': 'ARG',
  Caceres: 'ESP',
  Caen: 'FRA',
  Cagliari: 'ITA',
  Cali: 'COL',
  'Canet-en-Roussillon': 'FRA',
  'Cape Town': 'RSA',
  Castellon: 'ESP',
  Catania: 'ITA',
  'Chalon Sur Saone': 'FRA',
  'Chalon-Sur-Saone': 'FRA',
  Charlotte: 'USA',
  Cholet: 'FRA',
  'Corbeil-Essonnes': 'FRA',
  Corfu: 'GRE',
  Coruna: 'ESP',
  Crawley: 'GBR',
  Dallas: 'USA',
  Darmstadt: 'GER',
  Debrecen: 'HUN',
  'Don Benito': 'ESP',
  Donostia: 'ESP',
  'Dos Hermanas': 'ESP',
  Drachten: 'NED',
  Dubai: 'UAE',
  Dunkerque: 'FRA',
  Durban: 'RSA',
  Etobicoke: 'CAN',
  Ettelbruck: 'LUX',
  Ferrol: 'ESP',
  Florence: 'ITA',
  'Fort Laudardale': 'USA',
  Fukuoka: 'JPN',
  Fullerton: 'USA',
  Gelsenkirchen: 'GER',
  Genova: 'ITA',
  Gothenburg: 'SWE',
  Granada: 'ESP',
  Guaratingueta: 'BRA',
  Gyoer: 'HUN',
  'High Wycombe': 'GBR',
  Hillcrest: 'RSA',
  Hodmezovasarhely: 'HUN',
  'Hong Kong': 'HKG',
  Jaen: 'ESP',
  Karlsruhe: 'GER',
  Keller: 'USA',
  Kiev: 'UKR',
  Kranj: 'SLO',
  Kreuzlingen: 'SUI',
  'La Teste-De-Buch': 'FRA',
  Laeken: 'BEL',
  'Las Palmas de G.C': 'ESP',
  'Las Palmas G.C': 'ESP',
  Laval: 'FRA',
  'Le Bouscat': 'FRA',
  'Le Mont sur Lausanne': 'SUI',
  Lignano: 'ITA',
  'Lignano Sabbiadoro': 'ITA',
  Lilongwe: 'MAW',
  Limassol: 'CYP',
  Linz: 'AUT',
  Lodi: 'ITA',
  Loerrach: 'GER',
  London: 'GBR',
  'Luxembourg/Hollerich': 'LUX',
  'Mairena Aljarafe': 'ESP',
  Maliano: 'ESP',
  Manchester: 'GBR',
  Mansfield: 'GBR',
  Maribor: 'SLO',
  Marrakech: 'MAR',
  Marseille: 'FRA',
  Melbourne: 'AUS',
  Melilla: 'ESP',
  Mococa: 'BRA',
  Molenbeek: 'BEL',
  'Monte-Carlo': 'MON',
  Montreal: 'CAN',
  Mostoles: 'ESP',
  Mulhouse: 'FRA',
  Munich: 'GER',
  Naron: 'ESP',
  Neckarsulm: 'GER',
  Neuchatel: 'SUI',
  Nicosia: 'CYP',
  Oberkirch: 'GER',
  Orsay: 'FRA',
  Ourense: 'ESP',
  Palermo: 'ITA',
  Palhoca: 'BRA',
  'Palma de Mallorca': 'ESP',
  'Palma De Mallorca': 'ESP',
  Paphos: 'CYP',
  Perth: 'AUS',
  Pietermaritzburg: 'RSA',
  Piraeus: 'GRE',
  Ponteareas: 'ESP',
  Poznan: 'POL',
  Prilly: 'SUI',
  Recife: 'BRA',
  Reykjavik: 'ISL',
  Riccione: 'ITA',
  Riga: 'LAT',
  'Rio de Janeiro': 'BRA',
  Samorin: 'SVK',
  Sandnes: 'NOR',
  'Sao Paulo': 'BRA',
  Sarcelles: 'FRA',
  Seoul: 'KOR',
  Seraing: 'BEL',
  Sevilha: 'ESP',
  Sevilla: 'ESP',
  Sheffield: 'GBR',
  Sicilia: 'ITA',
  Singapore: 'SGP',
  Skopje: 'MKD',
  Sonderborg: 'DEN',
  Stadskanaal: 'NED',
  Stratford: 'GBR',
  Stuttgart: 'GER',
  Szczecin: 'POL',
  Tarbes: 'FRA',
  Thionville: 'FRA',
  Tilburg: 'NED',
  Toronto: 'CAN',
  Torremolinos: 'ESP',
  Toulouse: 'FRA',
  Trieste: 'ITA',
  Unionville: 'CAN',
  Valencia: 'ESP',
  Valetta: 'MLT',
  Valladolid: 'ESP',
  Vigo: 'ESP',
  'Viry-Chatillon': 'FRA',
  Wachtebeke: 'BEL',
  Wien: 'AUT',
  Wingate: 'ISR',
};

// "Gijon (ESP)" for foreign cities; plain city name for Portuguese ones.
export function formatCity(city) {
  if (!city) return '';
  const code = CITY_COUNTRY[city];
  return code ? `${city} (${code})` : city;
}
